name: Build

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build tools
      run: pip install build setuptools-scm

    - name: Build wheel
      run: python -m build --wheel

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: pypylon-contrib-wheel
        path: dist/*.whl
